name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian-jetson-nano:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "bookworm"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "jetson-nano"                   # build target

  build-armbian-pather-x2:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "bookworm"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "panther-x2"                   # build target